[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"

[registration]
[registration.email]
