[logging]
log_level = "info"

[tracker]
api_url = "http://tracker:1212"
mode = "private"
url = "http://tracker:7070"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/e2e_testing_sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"
