version = "2"

[core]
private = true

[core.database]
driver = "Sqlite3"
path = "/var/lib/torrust/tracker/database/e2e_testing_sqlite3.db"

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[http_api]
bind_address = "0.0.0.0:1212"

