name: Development Checks

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --all --check
      - name: Check
        run: cargo check --all-targets
      - name: Clippy
        run: cargo clippy --all-targets
      - name: Unit and integration tests
        run: cargo test --all-targets
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Test Coverage
        run: cargo llvm-cov nextest
      - name: E2E Tests
        run: ./docker/bin/run-e2e-tests.sh
